export enum StateOptions {
	INITIAL = "INITIAL",
	PENDING = "PENDING",
	FULFILLED = "FULFILLED",
	REJECTED = "REJECTED",
	IDLE = "IDLE",
}

export enum CapacityPlanLevel {
	INDIVIDUAL = "INDIVIDUAL",
	INSTITUTIONAL = "INSTITUTIONAL",
	ORGANIZATIONAL = "ORGANIZATIONAL",
}

export enum CapacityPlanStatus {
	DRAFT = "DRAFT",
	SENT = "SENT",
	UNDER_REVIEW = "UNDER_REVIEW",
	APPROVED = "APPROVED",
	REJECTED = "REJECTED",
}


export enum TrainingStatus {
	PENDING = "PENDING",
	APPROVED = "APPROVED",
	REJECTED = "REJECTED",
	FINISHED = "FINISHED",
}

export enum CapacityPlanType {
	ANNUAL_PLAN = "ANNUAL_PLAN",
	QUARTELY_PLAN = "QUARTELY_PLAN",
	ESSENTIAL_PLAN = "ESSENTIAL_PLAN",
}

export enum EmployeeTrainingStatus {
	PENDING = "PENDING",
	APPROVED = "APPROVED",
	REJECTED = "REJECTED",
	FINISHED = "FINISHED",
}

export enum AssessmentStatus {
	DRAFT = "DRAFT",
	SENT = "SENT",
	UNDER_REVIEW = "UNDER_REVIEW",
	REVIEWED = "REVIEWED",
}

